#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ContaTentoGom.Resource", IsApplication=true)]

namespace ContaTentoGom
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060000
			public const int theme_devicedefault_background = 2131099648;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int btn_style = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int btn_truco_reset = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070009
			public const int buttonAddT1 = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int buttonAddT2 = 2131165194;
			
			// aapt resource value: 0x7f070010
			public const int buttonReset = 2131165200;
			
			// aapt resource value: 0x7f07000c
			public const int buttonSubT1 = 2131165196;
			
			// aapt resource value: 0x7f07000e
			public const int buttonSubT2 = 2131165198;
			
			// aapt resource value: 0x7f07000d
			public const int buttonTruco = 2131165197;
			
			// aapt resource value: 0x7f070011
			public const int frameLayout1 = 2131165201;
			
			// aapt resource value: 0x7f07000f
			public const int relativeLayout1 = 2131165199;
			
			// aapt resource value: 0x7f070000
			public const int tableLayout1 = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int tableRow1 = 2131165185;
			
			// aapt resource value: 0x7f070005
			public const int tableRow2 = 2131165189;
			
			// aapt resource value: 0x7f070008
			public const int tableRow3 = 2131165192;
			
			// aapt resource value: 0x7f07000b
			public const int tableRow4 = 2131165195;
			
			// aapt resource value: 0x7f070002
			public const int textView10 = 2131165186;
			
			// aapt resource value: 0x7f070004
			public const int textView11 = 2131165188;
			
			// aapt resource value: 0x7f070003
			public const int textView16 = 2131165187;
			
			// aapt resource value: 0x7f070012
			public const int textView19 = 2131165202;
			
			// aapt resource value: 0x7f070006
			public const int textViewT1 = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int textViewT2 = 2131165191;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int config = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050001
			public const int Theme_Custom = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int button_text = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
